### ISSUE TITLE
Fix failure on systems with only Python 3.x

### ISSUE THREAD

**Issue by jecassis** [TheLartians/Format.cmake#14]
Due to a combination of [PEP 394](https://www.python.org/dev/peps/pep-0394/) and newer operating systems shipping with only Python 3.x (such as Ubuntu 20.04), `Format.cmake` may fail on [this line](https://github.com/TheLartians/Format.cmake/blob/3bef0a0ad9a3bc988a15e85839a2b10ea33e15cb/CMakeLists.txt#L6). The failure is due to the `python` executable not existing. Using CMake's `FindPython` module might make `Format.cmake` more portable and robust.

In the meantime, without installing Python 2.x, some workarounds are:

1. Alias `python` to `python3`, e.g.

```
echo 'alias python=python3' | sudo tee -a /etc/environment > /dev/null
```

2. Use alternatives to do the same, e.g.

```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
```

**Comment by TheLartians** [comment]
Hey, thanks for the report! The current version of Format.cmake (1.5.1) now uses `find_package(Python)` to get the python executable. Would be great if you can let me know if it works on your configuration.

**Comment by jecassis** [comment]
Thank you. I tested it and works as expected on both Windows 10 and Ubuntu 20.04.
