### ISSUE TITLE
Update About to mention cmake-format

### ISSUE THREAD

**Issue by johelegp** [TheLartians/Format.cmake#21]
![1608486911](https://user-images.githubusercontent.com/21071787/102720483-01261780-42cb-11eb-86f7-3ef947dc1aa5.png)
-------------
![1608486927](https://user-images.githubusercontent.com/21071787/102720489-0a16e900-42cb-11eb-9d35-cde825c83ae4.png)

**Comment by TheLartians** [comment]
Good point! I've updated the about section.
