### ISSUE TITLE
Check Format Fails on Windows

### ISSUE THREAD

**Issue by DeveloperPaul123** [TheLartians/Format.cmake#3]
I'm not sure if it's your intention to have this script be cross platform but the check format build target fails on Windows (by default) because `grep` is not available.

Another side effect of this is that your CMake project template will fail a `build all` action due to this format check.

**Comment by TheLartians** [comment]
Hey thanks for the issue, I wasn't aware that it fails on windows! Optimally it should work on all platforms. I don't have access to windows unfortunately but I'll try later if I can get a fix and CI test running. I think it shouldn't be too difficult use a more cross-platform way to determine the status.

**Comment by TheLartians** [comment]
Hey, I've updated the python script so that no grep is required in #4 . Unfortunately I haven't been able to install clang-format in a windows GitHub action, so it's still untested. It would be great if you could try if Version 1.1 works for you!

**Comment by TheLartians** [comment]
> Another side effect of this is that your CMake project template will fail a build all action due to this format check.

I think that the format targets are currently not added to the `all` target, so it should actually be fine.

**Comment by DeveloperPaul123** [comment]
Seems like it still fails but for a different reason. 

Is the script expecting to run from the root directory of the source of the project?

**Comment by TheLartians** [comment]
hm well the script uses git to find any source files, so it probably should be called from somewhere within the repo.

**Comment by DeveloperPaul123** [comment]
I normally build my cmake projects completely outside the source (git) directory. Would this cause a problem?

> Unfortunately I haven't been able to install clang-format in a windows GitHub action, so it's still untested.

You might be able to use [chocolatey](https://chocolatey.org) on the CI and then install clang-format with `choco install LLVM`.

**Comment by TheLartians** [comment]
> I normally build my cmake projects completely outside the source (git) directory. Would this cause a problem?

Oh yeah, in the current version probably yes. I didn't thought about that use-case when I created this. I think it could work if  I set the `WORKING_DIRECTORY` to `CMAKE_SOURCE_DIR` when calling the script.

> You might be able to use chocolatey on the CI and then install clang-format with choco install LLVM.

So THAT's what the package manager for windows is called! Thanks, it seems I suck at google. I'll try that out!

**Comment by DeveloperPaul123** [comment]
Ok I can give that a try but that should work I think. I had to issue a PR on a similar [project](https://github.com/zemasoft/clangformat-cmake) that had the same issue.

> So THAT's what the package manager for windows is called! Thanks, it seems I suck at google. I'll try that out!

Yup! It's not perfect but it's usable enough. I makes set up pretty easy and I use it on all my dev machines.

**Comment by DeveloperPaul123** [comment]
I just tried it out and adding `WORKING_DIRECTORY` to all the custom commands fixes the issues.

```cmake
set(CLANG_FORMAT_COMMAND python ${CMAKE_CURRENT_LIST_DIR}/git-clang-format.py)
set(GIT_EMPTY_TREE_HASH 4b825dc642cb6eb9a060e54bf8d69288fbee4904)

add_custom_target(format
  COMMAND ${CLANG_FORMAT_COMMAND} --diff ${GIT_EMPTY_TREE_HASH} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
)

add_custom_target(check-format
  COMMAND ${CLANG_FORMAT_COMMAND} --ci ${GIT_EMPTY_TREE_HASH} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
)

add_custom_target(fix-format
  COMMAND ${CLANG_FORMAT_COMMAND} ${GIT_EMPTY_TREE_HASH} -f WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
)
```

**Comment by TheLartians** [comment]
You were faster than me it seems 😉 thanks for testing it!
