### ISSUE TITLE
How to ignore file mode in check format?

### ISSUE THREAD

**Issue by RobertIndie** [TheLartians/Format.cmake#8]
In windows or WSL, when using format it outputs these results:

![image](https://user-images.githubusercontent.com/16974619/80946273-3d7e3380-8e20-11ea-90fa-3083bb13bd37.png)

and it makes check-format fail.

Is there any way to prevent file mode checking?

**Comment by TheLartians** [comment]
Hey thanks for the report, I agree that this shouldn't happen. I added a fix, however not having access to windows besides the Github CI I'm not sure if this actually works. Could you try with the following version and see if it fixes your issue?

```cmake
CPMAddPackage(
  NAME Format.cmake
  GITHUB_REPOSITORY TheLartians/Format.cmake
  GIT_TAG ad172043c3995edbccf55b2efd8c4e63dad6476a  
  VERSION 1.4-b
)
```

**Comment by RobertIndie** [comment]
No, it didn't work.

But according to [https://stackoverflow.com/questions/3290512/can-i-make-git-diff-ignore-permission-changes/16348658](https://stackoverflow.com/questions/3290512/can-i-make-git-diff-ignore-permission-changes/16348658)
![image](https://user-images.githubusercontent.com/16974619/80957238-5f35e580-8e35-11ea-9711-cb180917d3ef.png)

It seems it didn't work on committed files (like [https://github.com/TheLartians/ModernCppStarter](https://github.com/TheLartians/ModernCppStarter), the file mode in this repo seem to be 100644)

Also, I tried "git diff -G.", but it didn't work, it ignored all the diff changes.

**Comment by RobertIndie** [comment]
My temporary [solution ](https://github.com/RobertIndie/smark/commit/be994b465b4586fdf50db00fbed8556c3c203f47)is to change the file mode of all files to 100755 (In WSL, it automatically changed once cloned), and commit.

**Comment by TheLartians** [comment]
Hm it's still weird that the format script changes the file mode. I've added the ` -c core.fileMode=false` to ALL git calls in hope of preventing the file mode to being added to the formatted commit. Before we give up on the flag, it would be great if you can check it once more with `GIT_TAG 44d755c4e971c2270229ff137cf836b46acb1fd7`.

**Comment by TheLartians** [comment]
Ah I may have misunderstood, so the file mode is being changed by WSL **after** cloning but before clang-format? In that case the format script cannot know that clang-format didn't change the file permissions, as it uses the current git tree as a reference. In that case actually committing the changed modes might actually only real solution here, but perhaps setting the `fileMode` flag can still convince the script to ignore it.

**Comment by RobertIndie** [comment]
Yes, you're right. Thank you!

Besides, is it a good way to change the file mode of all files to 100755 in [ModernCppStarter repo](https://github.com/TheLartians/ModernCppStarter)?

**Comment by TheLartians** [comment]
> Yes, you're right. Thank you!

So did the script work, or are you referring to committing changes before format?

> Besides, is it a good way to change the file mode of all files to 100755 in ModernCppStarter repo?

Not sure I understand the question. AFAIK, the permissions in the repo currently are set to `-rw-r--r--` which I think is a reasonable value to have.

**Comment by RobertIndie** [comment]
No, it didn't work.

**Comment by TheLartians** [comment]
Darn, thanks for letting me know!

**Comment by RobertIndie** [comment]
I found a solution to avoid this issue without change file mode in WSL (for those working on WSL):

```shell
git config core.filemode true
cmake --build build --target check-format # format or check-format
git config core.filemode false
```

This is just a trick and should not merge in this project, just a temporary solution for those working on WSL.

**Comment by TheLartians** [comment]
Closing now due to inactivity. If this is still a recent issue that requires fixing, feel free to open it again.
